### ISSUE TITLE
Client immediately disconnects when running server in release mode

### ISSUE THREAD

**Issue by srmeier** [srmeier/KnightOnline#30]
Now that we can build the server files in release mode I've noticed that the client instantly gets disconnected immediately after completely logging into the game.

**Comment by Demircivi** [comment]
I found the issue, I guess. I'm new to the sources, so it could be wrong.

Check KOSocket.cpp (shared project) and go to 102. line. And you will find this code.
`
		if (!HandlePacket(pkt))
		{
			TRACE("%s: Handler for packet %X returned false\n", GetRemoteIP().c_str(), pkt.GetOpcode());
#ifndef _DEBUG
			goto error_handler;
#endif
		}`

Actually commenting `goto error_handler;` line solved the problem for me, but this won't be the actual fix for this. In my opinion Client sends an unhandled packet to Server, so since Server is in release mode, Server disconnects the Client.

**Comment by Demircivi** [comment]
545@GameProcMain.cpp(WarFare project)`
			BYTE byCmd = N3_TIME_NOTIFY;
			s_pSocket->Send(&byCmd, 1);`

Ah, alright. Since it's an empty packet, I guess Client & Server using this for keep-alive thing. I mean ping.

Adding these lines to the switch@285 line of User.cpp(GameServer project) will fix this issue.
`
	case WIZ_TIMENOTIFY:
		break;`
![image](https://cloud.githubusercontent.com/assets/22484255/24578155/8713c7d8-16e3-11e7-89fc-9bf280d2a16d.png)

**Comment by srmeier** [comment]
Very nice work! If this is your first time working with the source code then I am very impressed!

I think you're right that we should keep WIZ_TIMENOTIFY and just not respond. The client isn't expecting a response anyways so we should be good. And it would make sense that this is just a ping to make sure the connection is still active.

If you would like to have the fix attributed to you then push to your repo, create a merge request and I'll happily merge the code and close this ticket. Otherwise I can push the fix this time and we can get you sorted for merging in the future. (I just want to give you the opportunity to merge the fix if you would like)

**Comment by Demircivi** [comment]
Yes, this is the first time. I also do reverse engineering in a game called Silkroad Online, I'm familiar with these structures. I'd like to help. Thanks 👍!
I just come to home, and sorry for late answer. I don't know how to use Git. Do you use Skype, Telegram or something?

**Comment by srmeier** [comment]
That's cool, I have heard of Silkroad Online before but I have never played it. My Skype is "bitshift8", message me on there and I'll help you get setup with everything.

**Comment by srmeier** [comment]
Fixed by commit 578f0e3

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#30
