### ISSUE TITLE
Missing models

### ISSUE THREAD

**Issue by Demircivi** [srmeier/KnightOnline#37]
Some NPC and Monster models are missing.
E.g. Moradon Sundries
![image](https://cloud.githubusercontent.com/assets/22484255/24677273/ebabd8b8-198e-11e7-903e-c53cd1a04c97.png)
![image](https://cloud.githubusercontent.com/assets/22484255/24677670/3e969152-1990-11e7-993b-c0527deece0e.png)

**Comment by twostars** [comment]
Is this actually a problem with the client source though? Are they failing to render for some reason, or does the client data literally just not contain these models because they're too new?

If it's just a data issue, this isn't really something that needs addressing.

**Comment by srmeier** [comment]
Yeah I'm 90% sure this is just a data issue. If you have a TBL with a row for the NPC which the server sent you (and the content files for that NPC exist in your data) then this won't happen. And since the data we are working with is a bit more consistent now this shouldn't be happening very much. Going to go ahead and close this for now. @Demircivi if you notice something more to this issue feel free to open again.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#37
