### ISSUE TITLE
Issue with N3Sky not being large enough

### ISSUE THREAD

**Issue by srmeier** [srmeier/KnightOnline#59]
So I believe a lot of people are familiar with this issue

![pic00](https://cloud.githubusercontent.com/assets/680880/26262972/c08361ae-3ca4-11e7-9ebf-2c5e18aa8e16.png)

Turns out if you just make the render billboard larger it fixes this problem.

![pic01](https://cloud.githubusercontent.com/assets/680880/26263018/f1be6b92-3ca4-11e7-9bb2-bb5fcd842bd8.png)

Just opening and closing this issue so the solution gets documented.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#59

**Comment by GiladRe** [comment]
Hey Stephen,
As I remember when I was going through this, the idea behind creating this billboard was to create an illusion of far plane fog, because the originally pixel and vertex fog wasn't good enough.
What you basically did, is covering the skybox while the position of the billboard was in its correct place. So that doesn't really resolve the issue, as the sky box have different colors from the fog.
I don’t have a setup of the new changes since 1-year I guess, so I'll try to have another look at this, as I always wanted to fix this one and got some time before school starts again.
Will keep this post update if I find anything.

**Comment by GiladRe** [comment]
You can still see the breaking line between the sky box and the billboard if you change the camera rotation a bit more up (F9):
![capture](https://user-images.githubusercontent.com/17655494/30238475-a00f1c36-9548-11e7-876c-5b686901e5a7.PNG)

**Comment by GiladRe** [comment]
So i guess that does the trick? :)
The actual problem here was when we were setting a texture to the billboard with colors using the SetTextureState. The whole idea of the billboard, is to create an illusion of fog, so in order to let the vertices get drawn by the DrawPrimitiveUP, directx is expecting us to use the SetTexture function and we simply set it to null as we don’t need one. The SetFVF diffuse macro in combination with xyz, tells it to spread the colors around the xyz coordinates of the vertices, since each billboard(in this case front and bottom) has 4 corners.
It’s about time for the 12xx clients, no? ^_^
![capture](https://user-images.githubusercontent.com/17655494/30238815-370a11e4-954f-11e7-94f8-0a06d996fceb.PNG)

**Comment by GiladRe** [comment]
also fixed /time command in server and client, so we can debug the sky or some other stuff(cool sunset ^_^):
![capture](https://user-images.githubusercontent.com/17655494/30239119-badd4242-9555-11e7-8076-ad08e0bdd461.PNG)

**Comment by SavvyNik** [comment]
@GiladRe the sunset looks beautiful! Nice job 😄

**Comment by GiladRe** [comment]
@SavvyNik Oh my bad..I just realized it's sunrise as i was doing /time 5:25 ^_^

**Comment by SavvyNik** [comment]
Haha good catch! Now we wouldn't want to be wrong about the time of day since we got a time command lol
